[package]
name = "node-cli"
version = "3.0.0-dev"
authors = ["ZERO <play@zero.io>"]
description = "Generic Substrate node implementation in Rust."
build = "build.rs"
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"
default-run = "zero"
homepage = "https://zero.io"
repository = "https://github.com/playzero/zero-network/"

[package.metadata.wasm-pack.profile.release]
# `wasm-opt` has some problems on linux, see
# https://github.com/rustwasm/wasm-pack/issues/781 etc.
wasm-opt = false

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[badges]
travis-ci = { repository = "playzero/zero-network" }
maintenance = { status = "actively-developed" }
is-it-maintained-issue-resolution = { repository = "playzero/zero-network" }
is-it-maintained-open-issues = { repository = "playzero/zero-network" }

[[bin]]
name = "zero"
path = "bin/main.rs"
required-features = ["cli"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
# third-party dependencies
codec = { package = "parity-scale-codec", version = "2.0.0" }
serde = { version = "1.0.132", features = ["derive"] }
futures = "0.3.16"
hex-literal = "0.3.4"
log = "0.4.8"
rand = "0.7.2"
structopt = { version = "0.3.26", optional = true }

# primitives
sp-authority-discovery = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-consensus-babe = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
grandpa-primitives = { version = "4.0.0-dev", package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-core = { version = "4.1.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-runtime = { version = "4.0.0", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-timestamp = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-authorship = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-inherents = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-keyring = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-keystore = { version = "0.10.0", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-transaction-storage-proof = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

# client dependencies
sc-client-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-chain-spec = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-transaction-pool = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-transaction-pool-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-network = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-consensus-slots = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-consensus-babe = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-consensus-uncles = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
grandpa = { version = "0.10.0-dev", package = "sc-finality-grandpa", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-rpc = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-basic-authorship = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-service = { version = "0.10.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-telemetry = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-executor = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-authority-discovery = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-sync-state-rpc = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

# frame dependencies
frame-system = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
frame-system-rpc-runtime-api = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-transaction-payment = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-asset-tx-payment = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-im-online = { version = "4.0.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

# node-specific dependencies
node-runtime = { version = "3.0.0-dev", path = "../runtime" }
node-rpc = { version = "3.0.0-dev", path = "../rpc" }
node-primitives = { version = "2.0.0", path = "../primitives" }
node-executor = { version = "3.0.0-dev", path = "../executor" }

# CLI-specific dependencies
sc-cli = { version = "0.10.0-dev", optional = true, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
frame-benchmarking-cli = { version = "4.0.0-dev", optional = true, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

node-inspect = { version = "0.9.0-dev", optional = true, path = "../inspect" }

try-runtime-cli = { version = "0.10.0-dev", optional = true, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

[target.'cfg(any(target_arch="x86_64", target_arch="aarch64"))'.dependencies]
node-executor = { version = "3.0.0-dev", path = "../executor", features = [
	"wasmtime",
] }
sc-cli = { version = "0.10.0-dev", optional = true, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", features = [
	"wasmtime",
] }
sc-service = { version = "0.10.0-dev", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", features = [
	"wasmtime",
] }
sp-trie = { version = "4.0.0", default-features = false, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", features = [
	"memory-tracker",
] }

[dev-dependencies]
sc-keystore = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-client-db = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-consensus = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-consensus-babe = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-consensus-epochs = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-service-test = { version = "2.0.0", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-block-builder = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-tracing = { version = "4.0.0", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sp-blockchain = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
futures = "0.3.16"
tempfile = "3.1.0"
assert_cmd = "2.0.2"
nix = "0.23"
serde_json = "1.0"
regex = "1"
platforms = "2.0"
async-std = { version = "1.10.0", features = ["attributes"] }
soketto = "0.4.2"
criterion = { version = "0.3.5", features = [ "async_tokio" ] }
tokio = { version = "1.15", features = ["macros", "time"] }
jsonrpsee-ws-client = "0.4.1"
wait-timeout = "0.2"
remote-externalities = { git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
pallet-timestamp = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

[build-dependencies]
structopt = { version = "0.3.26", optional = true }
node-inspect = { version = "0.9.0-dev", optional = true, path = "../inspect" }

frame-benchmarking-cli = { version = "4.0.0-dev", optional = true, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
substrate-build-script-utils = { version = "3.0.0", optional = true, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
substrate-frame-cli = { version = "4.0.0-dev", optional = true, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
try-runtime-cli = { version = "0.10.0-dev", optional = true, git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }
sc-cli = { version = "0.10.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01", optional = true }
pallet-balances = { version = "4.0.0-dev", git = "https://github.com/paritytech/substrate", tag = "monthly-2022-01" }

[features]
default = ["cli"]
cli = [
	"node-executor/wasmi-errno",
	"node-inspect",
	"sc-cli",
	"frame-benchmarking-cli",
	"substrate-frame-cli",
	"sc-service/db",
	"structopt",
	"substrate-build-script-utils",
	"try-runtime-cli",
]
runtime-benchmarks = [
	"node-runtime/runtime-benchmarks",
	"frame-benchmarking-cli",
]
# Enable features that allow the runtime to be tried and debugged. Name might be subject to change
# in the near future.
try-runtime = ["node-runtime/try-runtime", "try-runtime-cli"]

[[bench]]
name = "transaction_pool"
harness = false

[[bench]]
name = "block_production"
harness = false
