[package]
name = "zero-bench"
version = "0.9.0-dev"
authors = ["ZERO <play@zero.io>"]
description = "Substrate node integration benchmarks."
edition = "2021"
license = "GPL-3.0-or-later WITH Classpath-exception-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
array-bytes = "4.1"
clap = { version = "4.0.9", features = ["derive"] }
log = "0.4.17"
zero-primitives = { version = "2.0.0", path = "../../../modules/primitives" }
node-testing = { version = "3.0.0-dev", path = "../testing" }
alphaville-runtime = { version = "3.0.0-dev", path = "../runtime" }
sc-client-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
sp-state-machine = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
serde = "1.0.136"
serde_json = "1.0.85"
derive_more = { version = "0.99.17", default-features = false, features = ["display"] }
kvdb = "0.13.0"
kvdb-rocksdb = "0.17.0"
sp-trie = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
sp-consensus = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
sc-basic-authorship = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
sp-inherents = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
sp-timestamp = { default-features = false, git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
sp-tracing = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
hash-db = "0.15.2"
tempfile = "3.1.0"
fs_extra = "1"
rand = { version = "0.8.5", features = ["small_rng"] }
lazy_static = "1.4.0"
parity-db = "0.4.3"
sc-transaction-pool = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
sc-transaction-pool-api = { git = "https://github.com/paritytech/polkadot-sdk", branch = "polkadot-v0.9.38" }
futures = { version = "0.3.21", features = ["thread-pool"] }
