version: "3.7"
services:
  relaychain-alice:
    image: parity/polkadot:v0.9.40
    user: "0:0"
    ports:
      - 9944:9944
      - 9933:9933
      - 30333:30333
    volumes:
      - "./chainspec:/chainspec"
      - "./tmp:/tmp"
    command:
      - --base-path=/tmp/relay/alice
      - --chain=/chainspec/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=alice
      - --alice
      - --rpc-methods=unsafe
      - --wasm-execution=compiled
      - --execution=wasm
      - --node-key=bf16b85cdce899363bb32e5baf1f2d58e967ac9bd97e8dd3bdc6df26e2cd35ee
    environment:
      RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
  relaychain-bob:
    image: parity/polkadot:v0.9.40
    user: "0:0"
    ports:
      - 9945:9944
      - 9934:9933
      - 30334:30333
    volumes:
      - "./chainspec:/chainspec"
      - "./tmp:/tmp"
    command:
      - --base-path=/tmp/relay/bob
      - --chain=/chainspec/rococo-local.json
      - --validator
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=bob
      - --bob
      - --rpc-methods=unsafe
      - --wasm-execution=compiled
      - --execution=wasm
    environment:
      RUST_LOG: parachain::candidate-backing=trace,parachain::candidate-selection=trace,parachain::pvf=trace,parachain::collator-protocol=trace,parachain::provisioner=trace
  parachain-alice:
    image: playzero/subzero:local
    # image: subzero:local
    user: "0:0"
    ports:
      - 9946:9944
      - 9935:9933
      - 30335:30333
    volumes:
      - "./chainspec:/chainspec"
      - "./tmp:/tmp"
    command:
      - /usr/local/bin/subzero
      - --chain=/chainspec/subzero-parachain-raw.json
      - --base-path=/tmp/parachain/alice
      - --ws-external
      - --rpc-external
      - --rpc-cors=all
      - --name=parachain-2000-0
      - --collator
      - --rpc-methods=unsafe
      - --force-authoring
      - --wasm-execution=compiled
      - --execution=wasm
      - --alice
      - --node-key=bb4c6473c146d05a48d8b87fcd15229b825031d0ff5cca3a94024861306fe7aa
      - --listen-addr=/ip4/0.0.0.0/tcp/30333
      - --
      - --chain=/chainspec/rococo-local.json
      # - --bootnodes=/dns/relaychain-alice/tcp/30333/p2p/12D3KooWEkXWjRHhoMXzj3gKzewqem5Kppg65vpK8qTsRTkoKf3A
      - --wasm-execution=compiled
      - --execution=wasm
    environment:
      RUST_LOG: sc_basic_authorship=trace,cumulus-consensus=trace,cumulus-collator=trace,collator_protocol=trace,collation_generation=trace,aura=debug,xcm=trace
