version: "3.7"

services:
  validator-a:
    ports:
      - "9944:9944"
      - "9615:9615"
    user: "0:0"
    volumes:
      - ${PWD}/tmp/alice:/tmp/alice
#      - ../../target/release/subzero:/usr/local/bin/subzero
#    image: parity/substrate
    image: playzero/subzero:latest
    networks:
      - internet
    command:
      - "/usr/local/bin/subzero"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000001"
      - "--base-path"
      - "/tmp/alice"
      # - "--chain=subzero"
      - "--port"
      - "30333"
      - "--validator"
      - "--alice"
      - "--bootnodes"
      - "/dns/validator-b/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      - "--prometheus-external"

  validator-b:
    image: playzero/subzero:latest
#    image: parity/substrate
    ports:
      - "9945:9944"
    user: "0:0"
    volumes:
      - ${PWD}/tmp/bob:/tmp/bob
#      - ../../target/release/subzero:/usr/local/bin/subzero
    networks:
      - internet
    command:
      - "/usr/local/bin/subzero"
      - "--node-key"
      - "0000000000000000000000000000000000000000000000000000000000000002"
      - "--base-path"
      - "/tmp/bob"
      # - "--chain=subzero"
      - "--port"
      - "30333"
      - "--validator"
      - "--bob"
      - "--bootnodes"
      - "/dns/validator-a/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
      - "--no-telemetry"
      - "--rpc-cors"
      - "all"
      # Not only bind to localhost.
      - "--unsafe-ws-external"
      - "--unsafe-rpc-external"
      # - "--log"
      # - "sub-libp2p=trace"
      - "--prometheus-external"

#   light-c:
#     image: playzero/subzero:latest
# #    image: parity/substrate
#     ports:
#       - "9946:9944"
   # volumes:
      # - tmp/light:/tmp/light
#  #     - ../../target/release/subzero:/usr/local/bin/subzero
#     networks:
#       - internet
#     command:
#       - "/usr/local/bin/subzero"
#       - "--node-key"
#       - "0000000000000000000000000000000000000000000000000000000000000003"
#       - "--base-path"
#       - "/tmp/light"
#       # - "--chain="
#       - "--port"
#       - "30333"
#       - "--light"
#       - "--bootnodes"
#       - "/dns/validator-a/tcp/30333/p2p/12D3KooWEyoppNCUx8Yx66oV9fJnriXwCcXwDDUA2kj6vnc6iDEp"
#       - "--bootnodes"
#       - "/dns/validator-b/tcp/30333/p2p/12D3KooWHdiAxVd8uMQR1hGWXccidmfCwLqcMpGwR6QcTP6QRMuD"
#       - "--no-telemetry"
#       - "--rpc-cors"
#       - "all"
#       # Not only bind to localhost.
#       - "--unsafe-ws-external"
#       - "--unsafe-rpc-external"
#       - "--log"
#       - "sub-libp2p=trace"
#       - "--prometheus-external"

  # prometheus:
  #   image: prom/prometheus
  #   networks:
  #     - internet
  #   ports:
  #     - "9090:9090"
  #   links:
  #     - validator-a:validator-a
  #     - validator-b:validator-b
  #     - light-c:light-c
  #   volumes:
  #     - ./prometheus/:/etc/prometheus/
  #   restart: always

  # grafana:
  #   image: grafana/grafana
  #   user: "104"
  #   depends_on:
  #     - prometheus
  #   networks:
  #     - internet
  #   ports:
  #     - 3001:3000
  #   volumes:
  #     - ./grafana/provisioning/:/etc/grafana/provisioning
  #     - ../monitoring/grafana-dashboards/:/etc/grafana/provisioning/dashboard-definitions
  #   restart: always

networks:
  network-a:
  internet:
